name: SimpleDrugs
version: 3.0.0
authors: [xxCoderforlife,FHR]
main: me.Coderforlife.Drugs.Main
commands:
    drugs:
        description: For Drugs yo
        usage: /drugs <command>
permissions:
    drugs.*:
     children:
      drugs.wheat: true
      drugs.sugar: true
      drugs.paper: true
      drugs.gun: true
      drugs.bone: true
      drugs.remove: true
      drugs.main: true
      drugs.changelog: true
      drugs.reload: true
    drugs.playercmds:
     children:
      drugs.main: true
      drugs.wheat: true
      drugs.sugar: true
      drugs.paper: true
      drugs.gun: true
      drugs.bone: true
      drugs.remove: true
    drugs.wheat:
        default: true
    drugs.sugar:
        default: true
    drugs.paper:
        default: true
    drugs.gun:
        default: true
    drugs.bone:
        default: true
    drugs.remove:
        default: true
    drugs.main:
        default: true
    drugs.changelog:
        default: op
    drugs.reload:
        default: op
